# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UrbanAreaDemandDialog
                                 A QGIS plugin
 Urban Area Demand
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-24
        git sha              : $Format:%H$
        copyright            : (C) 2023 by GALUP
        email                : chj.chen@ufl.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from pathlib import Path

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.gui import QgisInterface

import pandas as pd

from ..lib import config

FORM_CLASS, _ = uic.loadUiType(
    str(
        Path(__file__).resolve().parent / 
        "future_land_use_simulator_dlg_base.ui"
    )
)


class FutureLandUseSimulatorDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, iface: QgisInterface, parent=None):
        """Constructor."""
        super(FutureLandUseSimulatorDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.iface = iface

    def populate_district(self):
        reg_name = self.cb_region.currentText()
        if reg_name == "N/A":
            self.cb_district.clear()
            self.cb_district.setEditable(False)
        elif reg_name == "Ahafo":
            self.cb_district.clear()
            self.cb_district.addItems(config.ahafo)
        elif reg_name == "Ashanti":
            self.cb_district.clear()
            self.cb_district.addItems(config.ashanti)
        elif reg_name == "Bono":
            self.cb_district.clear()
            self.cb_district.addItems(config.bono)
        elif reg_name == "Bono East":
            self.cb_district.clear()
            self.cb_district.addItems(config.bono_east)
        elif reg_name == "Central":
            self.cb_district.clear()
            self.cb_district.addItems(config.central)
        elif reg_name == "Eastern":
            self.cb_district.clear()
            self.cb_district.addItems(config.eastern)
        elif reg_name == "Greater Accra":
            self.cb_district.clear()
            self.cb_district.addItems(config.accra)
        elif reg_name == "North East":
            self.cb_district.clear()
            self.cb_district.addItems(config.ne)
        elif reg_name == "Northern":
            self.cb_district.clear()
            self.cb_district.addItems(config.north)
        elif reg_name == "Oti":
            self.cb_district.clear()
            self.cb_district.addItems(config.oti)
        elif reg_name == "Savannah":
            self.cb_district.clear()
            self.cb_district.addItems(config.sav)
        elif reg_name == "Upper East":
            self.cb_district.clear()
            self.cb_district.addItems(config.ue)
        elif reg_name == "Upper West":
            self.cb_district.clear()
            self.cb_district.addItems(config.uw)
        elif reg_name == "Volta":
            self.cb_district.clear()
            self.cb_district.addItems(config.volta)
        elif reg_name == "Western":
            self.cb_district.clear()
            self.cb_district.addItems(config.western)
        elif reg_name == "Western North":
            self.cb_district.clear()
            self.cb_district.addItems(config.west_north)
        else:
            self.cb_district.clear()

    def read_pop_project(self):
        yr = self.cb_year.currentText()
        region = self.cb_region.currentText()
        district = self.cb_district.currentText()

        csv_path = Path(__file__).parents[1] / "data/un_pop_projection.csv"
        pop_df = pd.read_csv(csv_path)

        if yr in config.yr_selectable and district:
            if district == "Entire Region":
                pop_project = pop_df.loc[
                    pop_df["reg_prop"] == region, f"{yr}_dif"
                ].sum()
            else:  # district specific
                pop_project = pop_df.loc[
                    pop_df["dist"] == district, f"{yr}_dif"
                ].values[0]
            self.le_proj_pop.setText(str(pop_project))

    def disable_study_area(self):
        district_txt = self.cb_district.currentText()
        if district_txt == "N/A":
            self.file_area.setEnabled(True)
        else:
            self.file_area.setEnabled(False)

    def disable_yr(self):
        yr_drop = self.cb_year.currentText()
        if yr_drop == " ":
            self.le_year.setEnabled(True)
        else:
            self.le_year.setEnabled(False)
