# --- variables need to run GA ---
import pandas as pd
import numpy as np

base_df = None  # to be updated by user input from GUI
GRID_R = 198
GRID_C = 196

TEMP_PER_BORDER = 0
TEMP_PER_AG = 0.0038
TEMP_PER_CON = -0.0020
TEMP_PER_URB = 0.0103
TEMP_PER_WATER = 0
TEMP_PER_HERB = 0.0072
TEMP_TARGET = 2

PPL_PER_URB = 514
PPL_CURRENT = 4157733
PPL_GROWTH = 1000000

LU_INSUFFICIENT = (3,)
LU_EXCESS = (5,)

min_conf = 0
max_conf = GRID_C * GRID_R

# --- Column names for the input DataFrame ---
AG_SUIT = "ag_suit"  # agriculture suitability
CON_SUIT = "con_suit"  # conservation suitability
URB_SUIT = "urb_suit"  # urban suitability
CURRENT_LU = "current_lu"  # current land use

# --- GA parameters ---
CXPB = 0.6  # crossover probability
MUTPB = 0.5  # mutation probability
GEN_NUM = 100  # number of generations
POP_SIZE = 100  # population size

# --- Initial sampling probability for each land use ---
INIT_PROB_AG = {1: 0.1, 2: 0.2, 3: 0.7}
INIT_PROB_CON = {1: 0.1, 2: 0.1, 3: 0.8}
INIT_PROB_URB = {1: 0.1, 2: 0.3, 3: 0.6}
INIT_SAMPLE_SIZE = 3000  # number of cells changing its land use

temp_slope = pd.Series(
    (
        TEMP_PER_BORDER,
        TEMP_PER_AG,
        TEMP_PER_CON,
        TEMP_PER_URB,
        TEMP_PER_WATER,
        TEMP_PER_HERB,
    ),
    index=np.arange(0, 6),
)

no_region_or_district = ["N/A"]

ahafo = [
    "Entire Region",
    "Asuogyaman",
    "Asutifi North",
    "Atebubu Amantin",
    "Atiwa East",
    "Tempane",
    "Tolon",
]

ashanti = [
    "Entire Region",
    "Adansi North",
    "Adansi South",
    "Adentan",
    "Afigya Kwabre South",
    "Agona East",
    "Ahafo Ano South East",
    "Ahafo Ano South West",
    "Ahanta West",
    "Akwapim North",
    "Amansie South",
    "Amansie West",
    "Anloga",
    "Asante Akim South",
    "Asene Manso Akroso",
    "Ashaiman",
    "Assin Fosu",
    "Assin North",
    "Atwima Nwabiagya North",
    "Atwima Nwabiagya South",
    "Awutu Senya",
    "Awutu Senya East",
    "Berekum West",
    "Builsa North",
    "Builsa South",
    "Ekumfi",
    "Ellembelle",
    "Karaga (Karaga)",
    "Kwaebibirem",
    "Kwahu Afram Plains South",
    "Kwahu East",
    "Mpohor",
    "Okaikoi North",
    "Okere",
    "Old Tafo",
    "Prestea/Huni Valley",
    "Pru East",
    "Saboba",
    "Sene West",
    "Shai Osudoku",
    "Shama",
    "Sissala East",
    "Sissala West",
    "Tano North",
]

bono = [
    "Entire Region",
    "Bawku West",
    "Bia East",
    "Bia West",
    "Dormaa West (Nkran Nkwanta)",
    "East Gonja",
    "East Mamprusi",
    "Jasikan",
    "Jomoro",
    "Tarkwa-Nsuaem",
    "Tatale Sanguli",
    "Techiman",
]

bono_east = [
    "Entire Region",
    "Atiwa West",
    "Korle Klottey",
    "Kpandai",
    "North Dayi",
    "North East Gonja",
    "Savelugu",
    "Sawla Tuna Kalba",
    "South Dayi",
    "South Tongu",
    "Upper Denkyira East",
    "Upper Denkyira West",
]

central = [
    "Entire Region",
    "Abura Asebu Kwamankese",
    "Agona West",
    "Agortime-Ziope",
    "Akatsi North",
    "Asokwa",
    "Assin South",
    "Asunafo North",
    "Asunafo South",
    "Ayawaso Central",
    "Ayawaso East",
    "Central Tongu",
    "Ejura Sekyedumase",
    "Fanteakwa North",
    "Gomoa West",
    "Gushegu",
    "Ho",
    "Kpando",
    "Nadowli Kaleo",
    "Wa West",
    "Wassa Amenfi East",
    "Wassa Amenfi West",
    "Wassa East",
]

eastern = [
    "Entire Region",
    "Abuakwa North",
    "Abuakwa South",
    "Ada East",
    "Akwapim South",
    "Akyemansa",
    "Amansie Central",
    "Asikuma Odoben Brakwa",
    "Asutifi South",
    "Atwima Kwanwoma",
    "Atwima Mponua",
    "Bawku",
    "Birim South",
    "Bodi",
    "Bole",
    "Dormaa East",
    "Ga Central",
    "Ga East",
    "Kwahu South",
    "Kwahu West",
    "La Dade-Kotopon",
    "La Nkwantanang Madina",
    "Lambussie Karni",
    "Lawra",
    "Mion",
    "Nkoranza South",
    "Nkwanta North",
    "Offinso",
    "Pusiga",
    "Tano South",
    "Weija Gbawe",
    "Wenchi",
]

accra = [
    "Entire Region",
    "Ablekuma Central",
    "Ablekuma North",
    "Ablekuma West",
    "Achiase",
    "Ada West",
    "Adaklu",
    "Afadzato South",
    "Asokore Mampong",
    "Ayawaso North",
    "Ayawaso West",
    "Ayensuano",
    "Banda",
    "Ga North",
    "Ga South",
    "Ga West",
    "Garu",
    "Gomoa Central",
    "Kpone Katamanso",
    "Krachi West",
    "Kwadaso",
    "Ledzokuku",
    "Lower Manya Krobo",
    "Mfantsiman",
    "Nkwanta South",
    "Pru West",
    " Suaman",
    "Upper Manya Krobo",
    "Zabzugu",
]

ne = [
    "Entire Region",
    "Central Gonja",
    "Effutu",
    "Nabdam",
]

north = [
    "Entire Region",
    "Denkyembuor",
    "Ho West",
    "Keta",
    "Krachi East",
    "Kwahu Afram Plains North",
    "Nandom",
    "New Juaben South",
    "Ningo Prampram",
    "Nkoranza North",
    "Sefwi Wiawso",
    "Sekyere Afram Plains",
    "Sekyere Central",
    "Tema West",
    "Twifo Heman Lower Denkyira",
    "Wa",
]

oti = [
    "Entire Region",
    "Binduri",
    "Juaben",
    "Kasena Nankana West",
    "Krowor",
    "Kumbungu",
    "Kwabre East",
    "North Gonja",
    "North Tongu",
]

sav = [
    "Entire Region",
    "Bolgatanga",
    "Chereponi",
    "Effia Kwesimintsim",
    "Nzema East",
    "Offinso North",
    "Sekyere East",
]

ue = [
    "Entire Region",
    "Bekwai",
    "Berekum East",
    "Birim North",
    "Bongo",
    "Bosome Freho",
    "Bosomtwe",
    "Bunkpurugu Nakpanduri",
    "Cape Coast Metro",
    "Gomoa East",
    "Ketu North",
    "Ketu South",
    "Nanumba North",
    "Sefwi Akontombra",
    "Techiman North",
    "Wa East",
]

uw = [
    "Entire Region",
    "Dormaa Central",
    "Juaboso",
    "Mampong",
    "Mamprugu Moagduri",
    "Nanumba South",
    "New Juaben North",
    "Suhum",
    "Sunyani",
    "West Akim",
    "West Gonja",
    "West Mamprusi",
]

volta = [
    "Entire Region",
    "Adansi Asokwa",
    "Afigya Kwabre North",
    "Ahafo Ano North",
    "Akatsi South",
    "Akrofuom",
    "Asante Akim Central",
    "Daffiama Bussie Issa",
    "Hohoe",
    "Jaman North",
    "Jaman South",
    "Kintampo North",
    "Kintampo South",
    "Komenda Edina Eguafo Abirem",
    "Krachi Nchumuru",
    "Nsawam Adoagyiri",
    "Obuasi East",
    "Sunyani West",
    "Tain",
]

western = [
    "Entire Region",
    "Ajumako Enyan Essiam",
    "Aowin",
    "Ejisu",
    "Fanteakwa South",
    "Kadjebi",
    "Nanton",
    "Oforikrom",
    "Sagnarigu",
    "Sene East",
    "Suame",
    "Twifo Ati Morkwa",
    "Yendi",
    "Yilo Krobo",
    "Yunyoo Nasuan",
]

west_north = [
    "Entire Region",
    "Asante Akim North",
    "Biakoye",
    "Bibiani Anhwiaso Bekwai",
    "Birim Central",
    "Bolgatanga East",
    "Kasena Nankana",
    "Sekyere Kumawu",
    "Sekyere South",
    "Talensi",
]

yr_selectable = [
    "2020",
    "2025",
    "2030",
    "2035",
    "2040",
    "2045",
    "2050",
    "2055",
    "2060",
    "2065",
    "2070",
    "2075",
    "2080",
    "2085",
    "2090",
    "2095",
    "2100",
]


dist_dict = {
    "Ablekuma North": "ABLEKUMA NORTH DISTRICT ASSEMBLY",
    "Ablekuma West": "ABLEKUMA WEST MUNICIPAL ASSEMBLY",
    "Abuakwa North": "ABUAKWA NORTH DISTRICT ASSEMBLY",
    "Abuakwa South": "ABUAKWA SOUTH MUNICIPAL ASSEMBLY",
    "Abura Asebu Kwamankese": "ABURA/ASEBU/KWAMANKESE DISTRICT ASSEMBLY",
    "Achiase": "ACHIASE DISTRICT ASSEMBLY",
    "Ada East": "ADA EAST DISTRICT ASSEMBLY",
    "Ada West": "ADA WEST MUNICIPAL ASSEMBLY",
    "Adaklu": "ADAKLU DISTRICT ASSEMBLY",
    "Adansi Asokwa": "ADANSI ASOKWA DISTRICT ASSEMBLY",
    "Adansi North": "ADANSI NORTH DISTRICT ASSEMBLY",
    "Adansi South": "ADANSI SOUTH DISTRICT ASSEMBLY",
    "Adentan": "ADENTAN MUNICIPAL ASSEMBLY",
    "Afadzato South": "AFADJATO SOUTH DISTRICT ASSEMBLY",
    "Afigya Kwabre North": "AFIGYA-KWABRE NORTH DISTRICT ASSEMBLY",
    "Afigya Kwabre South": "AFIGYA KWABRE SOUTH DISTRICT ASSEMBLY",
    "Agona East": "AGONA EAST DISTRICT ASSEMBLY",
    "Agona West": "AGONA WEST MUNICIPAL ASSEMBLY",
    "Agortime-Ziope": "AGORTIME ZIOPE DISTRICT ASSEMBLY",
    "Ahafo Ano North": "AHAFO ANO NORTH MUNICIPAL ASSEMBLY",
    "Ahafo Ano South East": "AHAFO ANO SOUTH EAST DISTRICT ASSEMBLY",
    "Ahafo Ano South West": "AHAFO ANO SOUTH-WEST DISTRICT ASSEMBLY",
    "Ahanta West": "AHANTA WEST MUNICIPAL ASSEMBLY",
    "Ajumako Enyan Essiam": "AJUMAKO/ENYAN/ESSIAM DISTRICT ASSEMBLY",
    "Akatsi North": "AKATSI NORTH DISTRICT ASSEMBLY",
    "Akatsi South": "AKATSI DISTRICT ASSEMBLY",
    "Akrofuom": "AKROFUOM DISTRICT ASSEMBLY",
    "Akwapim North": "AKUAPIM NORTH MUNICIPAL DISTRICT ASSEMBLY",
    "Akwapim South": "AKUAPIM SOUTH DISTRICT ASSEMBLY",
    "Akyemansa": "AKYEMANSA DISTRICT ASSEMBLY",
    "Amansie Central": "AMANSIE CENTRAL DISTRICT ASSEMBLY",
    "Amansie South": "AMANSIE SOUTH DISTRICT ASSEMBLY",
    "Amansie West": "AMANSIE WEST DISTRICT ASSEMBLY",
    "Anloga": "ANLOGA DISTRICT ASSEMBLY",
    "Aowin": "AOWIN MUNICIPAL ASSEMBLY",
    "Asante Akim Central": "ASANTE AKIM CENTRAL MUNICIPAL ASSEMBLY",
    "Asante Akim North": "ASANTE AKIM NORTH DISTRICT ASSEMBLY",
    "Asante Akim South": "ASANTE AKIM SOUTH MUNICIPAL ASSEMBLY",
    "Asene Manso Akroso": "ASENE-MANSO-AKROSO DISTRICT ASSEMBLY",
    "Ashaiman": "ASHAIMAN MUNICIPAL ASSEMBLY",
    "Asikuma Odoben Brakwa": "ASIKUMA/ODOBEN/BRAKWA DISTRICT ASSEMBLY",
    "Asokore Mampong": "ASOKORE MAMPONG MUNICIPAL ASSEMBLY",
    "Asokwa": "ASOKWA MUNICIPAL ASSEMBLY",
    "Assin Fosu": "ASSIN CENTRAL MUNICIPAL ASSEMBLY",
    "Assin North": "ASSIN NORTH MUNICIPAL ASSEMBLY",
    "Assin South": "ASSIN SOUTH DISTRICT ASSEMBLY",
    "Asunafo North": "ASUNAFO NORTH MUNICIPAL ASSEMBLY",
    "Asunafo South": "ASUNAFO SOUTH DISTRICT ASSEMBLY",
    "Asuogyaman": "ASUOGYAMAN DISTRICT ASSEMBLY",
    "Asutifi North": "ASUTIFI NORTH DISTRICT ASSEMBLY",
    "Asutifi South": "ASUTIFI SOUTH DISTRICT ASSEMBLY",
    "Atebubu Amantin": "ATEBUBU-AMANTIN MUNICIPAL ASSEMBLY",
    "Atiwa East": "ATIWA EAST DISTRICT ASSEMBLY",
    "Atiwa West": "ATIWA WEST DISTRICT ASSEMBLY",
    "Atwima Kwanwoma": "ATWIMA KWANWOMA DISTRICT ASSEMBLY",
    "Atwima Mponua": "ATWIMA MPONUA DISTRICT ASSEMBLY",
    "Atwima Nwabiagya North": "ATWIMA NWABIAGYA NORTH DISTRICT ASSEMBLY",
    "Atwima Nwabiagya South": "ATWIMA NWABIAGYA MUNICIPAL ASSEMBLY",
    "Awutu Senya": "AWUTU SENYA DISTRICT ASSEMBLY",
    "Awutu Senya East": "AWUTU SENYA EAST MUNICIPAL ASSEMBLY",
    "Ayawaso Central": "AYAWASO CENTRAL MUNICIPAL ASSEMBLY",
    "Ayawaso East": "AYAWASO EAST DISTRICT ASSEMBLY",
    "Ayawaso North": "AYAWASO NORTH MUNICIPAL ASSEMBLY",
    "Ayawaso West": "AYAWASO WEST DISTRICT ASSEMBLY",
    "Ayensuano": "AYENSUANO DISTRICT ASSEMBLY",
    "Banda": "BANDA DISTRICT ASSEMBLY",
    "Bawku": "BAWKU MUNICIPAL ASSEMBLY",
    "Bawku West": "BAWKU WEST DISTRICT ASSEMBLY",
    "Bekwai": "BEKWAI ASANTE MUNICIPAL ASSEMBLY",
    "Berekum East": "BEREKUM EAST MUNICIPAL ASSEMBLY",
    "Berekum West": "BEREKUM WEST DISTRICT ASSEMBLY",
    "Bia East": "BIA EAST DISTRICT ASSEMBLY",
    "Bia West": "BIA WEST DISTRICT ASSEMBLY",
    "Biakoye": "BIAKOYE NKONYA DISTRICT ASSEMBLY",
    "Bibiani Anhwiaso Bekwai": "BIBIANI-AHWIASO-BEKWAI MUNICIPAL ASSEMBLY",
    "Binduri": "BINDURI DISTRICT ASSEMBLY",
    "Birim Central": "BIRIM CENTRAL MUNICIPAL ASSEMBLY",
    "Birim North": "BIRIM NORTH DISTRICT ASSEMBLY",
    "Birim South": "BIRIM SOUTH DISTRICT ASSEMBLY",
    "Bodi": "BODI DISTRICT ASSEMBLY",
    "Bole": "BOLE DISTRICT ASSEMBLY",
    "Bolgatanga": "BOLGATANGA MUNICIPAL ASSEMBLY",
    "Bolgatanga East": "BOLGATANGA EAST DISTRICT ASSEMBLY",
    "Bongo": "BONGO DISTRICT ASSEMBLY",
    "Bosome Freho": "BOSOME FREHO DISTRICT ASSEMBLY",
    "Bosomtwe": "BOSOMTWE /ATWIMA / KWANWOMA",
    "Builsa North": "BUILSA NORTH DISTRICT ASSEMBLY",
    "Builsa South": "BUILSA SOUTH DISTRICT ASSEMBLY",
    "Bunkpurugu Nakpanduri": "BUNKPRUGU DISTRICT ASSEMBLY",
    "Cape Coast Metro": "CAPE COAST METROPOLITAN ASSEMBLY",
    "Central Gonja": "CENTRAL GONJA DISTRICT ASSEMBLY",
    "Central Tongu": "CENTRAL TONGU DISTRICT ASSEMBLY",
    "Chereponi": "CHEREPONI DISTRICT ASSEMBLY",
    "Daffiama Bussie Issa": "DAFFIAMA-BUSSIE-ISSA DISTRICT ASSEMBLY",
    "Denkyembuor": "DENKYEMBOUR DISTRICT ASSEMBLY",
    "Dormaa Central": "DORMAA CENTRAL MUNICIPAL ASSEMBLY",
    "Dormaa East": "DORMAA EAST DISTRICT ASSEMBLY",
    "Dormaa West (Nkran Nkwanta)": "DORMAA WEST DISTRICT ASSEMBLY",
    "East Gonja": "EAST GONJA MUNICIPAL  ASSEMBLY",
    "East Mamprusi": "EAST MAMPRUSI MUNICIPAL  ASSEMBLY",
    "Effia Kwesimintsim": "EFFIA/KWESIMINTSIM MUNICIPAL ASSEMBLY",
    "Effutu": "EFFUTU MUNICIPAL ASSEMBLY",
    "Ejisu": "EJISU MUNICIPAL ASSEMBLY",
    "Ejura Sekyedumase": "EJURA SEKYEDUMASE DISTRICT ASSEMBLY",
    "Ekumfi": "EKUMFI DISTRICT ASSEMBLY",
    "Ellembelle": "ELLEMBELE DISTRICT ASSEMBLY",
    "Fanteakwa North": "FANTEAKWA DISTRICT ASSEMBLY",
    "Fanteakwa South": "FANTEAKWA SOUTH DISTRICT ASSEMBLY",
    "Ga Central": "GA CENTRAL MUNICIPAL ASSEMBLY",
    "Ga East": "GA EAST MUNICIPAL ASSEMBLY",
    "Ga North": "GA NORTH MUNICIPAL ASSEMBLY",
    "Ga South": "GA SOUTH DISTRICT ASSEMBLY",
    "Ga West": "GA WEST MUNICIPAL ASSEMBLY",
    "Garu": "GARU DISTRICT ASSEMBLY",
    "Gomoa Central": "GOMOA CENTRAL MUNICIPAL ASSEMBLY",
    "Gomoa East": "GOMOA EAST DISTRICT ASSEMBLY",
    "Gomoa West": "GOMOA WEST DISTRICT ASSEMBLY",
    "Gushegu": "GUSHIEGU MUNICIPAL  ASSEMBLY",
    "Ho": "HO MUNICIPAL ASSEMBLY",
    "Ho West": "HO WEST DISTRICT ASSEMBLY",
    "Hohoe": "HOHOE MUNICIPAL ASSEMBLY",
    "Jaman North": "JAMAN NORTH DISTRICT ASSEMBLY",
    "Jaman South": "JAMAN SOUTH MUNICIPAL ASSEMBLY",
    "Jasikan": "JASIKAN DISTRICT ASSEMBLY",
    "Jomoro": "JOMORO MUNICIPAL ASSEMBLY",
    "Juaben": "JUABEN MUNICIPAL ASSEMBLY",
    "Juaboso": "JUABOSO DISTRICT ASSEMBLY",
    "Kadjebi": "KADJEBI DISTRICT ASSEMBLY",
    "Karaga (Karaga)": "KARAGA DISTRICT ASSEMBLY",
    "Kasena Nankana": "KASSENA NANKANA MUNICIPAL ASSEMBLY",
    "Kasena Nankana West": "KASSENA NANKANA WEST DISTRICT ASSEMBLY",
    "Keta": "KETA MUNICIPAL ASSEMBLY",
    "Ketu North": "KETU NORTH MUNICIPAL ASSEMBLY",
    "Ketu South": "KETU SOUTH DISTRICT ASSEMBLY",
    "Kintampo North": "KINTAMPO NORTH MUNICIPAL ASSEMBLY",
    "Kintampo South": "KINTAMPO SOUTH DISTRICT ASSEMBLY",
    "Komenda Edina Eguafo Abirem": "KOMENDA/EDINA/EGUAFO/ ABIREM MUNICIPAL ASSEMBLY",
    "Korle Klottey": "KORLE-KLOTTEY MUNICIPAL ASSEMBLY",
    "Kpandai": "KPANDAI DISTRICT ASSEMBLY",
    "Kpando": "KPANDO MUNICIPAL ASSEMBLY",
    "Kpone Katamanso": "KPONE-KATAMANSO MUNICIPAL ASSEMBLY",
    "Krachi East": "KRACHI EAST MUNICIPAL ASSEMBLY",
    "Krachi Nchumuru": "KRACHI NCHUMURU DISTRICT ASSEMBLY",
    "Krachi West": "KRACHI WEST DISTRICT ASSEMBLY",
    "Krowor": "KROWOR DISTRICT ASSEMBLY",
    "Kumbungu": "KUMBUNGU DISTRICT ASSEMBLY",
    "Kwabre East": "KWABRE EAST MUNICIPAL ASSEMBLY",
    "Kwadaso": "KWADASO MUNICIPAL ASSEMBLY",
    "Kwaebibirem": "KWAEBIBIREM MUNICIPAL ASSEMBLY",
    "Kwahu Afram Plains North": "KWAHU AFRAM PLAINS NORTH DISTRICT ASSEMBLY",
    "Kwahu Afram Plains South": "KWAHU AFRAM PLAINS SOUTH DISTRICT ASSEMBLY",
    "Kwahu East": "KWAHU EAST DISTRICT ASSEMBLY",
    "Kwahu South": "KWAHU SOUTH DISTRICT ASSEMBLY",
    "Kwahu West": "KWAHU WEST MUNICIPAL ASSEMBLY",
    "La Dade-Kotopon": "LA DADE-KOTOPON MUNICIPAL ASSEMBLY",
    "La Nkwantanang Madina": "LA NKWANTANANG-MADINA MUNICIPAL ASSEMBLY",
    "Lambussie Karni": "LAMBUSSIE DISTRICT ASSEMBLY",
    "Lawra": "LAWRA MUNICIPAL ASSEMBLY",
    "Ledzokuku": "LEDZEKUKU MUNICIPAL ASSEMBLY",
    "Lower Manya Krobo": "LOWER MANYA KROBO DISTRICT ASSEMBLY",
    "Mampong": "MAMPONG MUNICIPAL ASSEMBLY",
    "Mamprugu Moagduri": "MAMPRUGU-MOAGDURI DISTRICT ASSEMBLY",
    "Mfantsiman": "MFANTSIMAN MUNICIPAL ASSEMBLY",
    "Mion": "MION DISTRICT ASSEMBLY",
    "Mpohor": "MPOHOR DISTRICT ASSEMBLY",
    "Nabdam": "NABDAM DISTRICT ASSEMBLY",
    "Nadowli Kaleo": "NADOWLI-KALEO DISTRICT ASSEMBLY",
    "Nandom": "NANDOM DISTRICT ASSEMBLY",
    "Nanton": "NANTON DISTRICT ASSEMBLY",
    "Nanumba North": "NANUMBA NORTH MUNICIPAL  ASSEMBLY",
    "Nanumba South": "NANUMBA SOUTH DISTRICT ASSEMBLY",
    "New Juaben North": "NEW JUABEN NORTH MUNICIPAL DISTRICT ASSEMBLY",
    "New Juaben South": "NEW JUABEN SOUTH MUNICIPAL ASSEMBLY",
    "Ningo Prampram": "NINGO-PRAMPRAM DISTRICT ASSEMBLY",
    "Nkoranza North": "NKORANZA NORTH DISTRICT ASSEMBLY",
    "Nkoranza South": "NKORANZA SOUTH MUNICIPAL ASSEMBLY",
    "Nkwanta North": "NKWANTA NORTH DISTRICT ASSEMBLY",
    "Nkwanta South": "NKWANTA SOUTH MUNICIPAL ASSEMBLY",
    "North Dayi": "NORTH DAYI DISTRICT ASSEMBLY",
    "North East Gonja": "NORTH-EAST GONJA DISTRICT ASSEMBLY",
    "North Gonja": "NORTH GONJA DISTRICT ASSEMBLY",
    "North Tongu": "NORTH TONGU DISTRICT ASSEMBLY",
    "Nsawam Adoagyiri": "NSAWAM ADOAGYIRI MUNICIPAL ASSEMBLY",
    "Nzema East": "NZEMA EAST MUNICIPAL ASSEMBLY",
    "Obuasi East": "OBUASI EAST DISTRICT ASSEMBLY",
    "Offinso": "OFFINSO SOUTH MUNICIPAL ASSEMBLY",
    "Offinso North": "OFFINSO NORTH DISTRICT ASSEMBLY",
    "Oforikrom": "OFORIKROM MUNICIPAL ASSEMBLY",
    "Okaikoi North": "OKAIKWEI NORTH DISTRICT ASSEMBLY",
    "Okere": "OKERE DISTRICT ASSEMBLY",
    "Old Tafo": "OLD TAFO MUNICIPAL ASSEMBLY",
    "Prestea/Huni Valley": "PRESTEA-HUNI VALLEY MUNICIPAL ASSEMBLY",
    "Pru East": "PRU EAST DISTRICT ASSEMBLY",
    "Pru West": "PRU WEST DISTRICT ASSEMBLY",
    "Pusiga": "PUSIGA DISTRICT ASSEMBLY",
    "Saboba": "SABOBA DISTRICT ASSEMBLY",
    "Sagnarigu": "SAGNERIGU MUNICIPAL ASSEMBLY",
    "Savelugu": "SAVELUGU DISTRICT ASSEMBLY",
    "Sawla Tuna Kalba": "SAWLA-TUNA-KALBA DISTRICT ASSEMBLY",
    "Sefwi Akontombra": "SEFWI AKONTOMBRA DISTRICT ASSEMBLY",
    "Sefwi Wiawso": "SEFWI-WIAWSO MUNICIPAL ASSEMBLY",
    "Sekyere Afram Plains": "SEKYERE AFRAM PLAINS DISTRICT ASSEMBLY",
    "Sekyere Central": "SEKYERE CENTRAL DISTRICT ASSEMBLY",
    "Sekyere East": "SEKYERE EAST DISTRICT ASSEMBLY",
    "Sekyere Kumawu": "SEKYERE KUMAWU DISTRICT ASSEMBLY",
    "Sekyere South": "SEKYERE SOUTH DISTRICT ASSEMBLY",
    "Sene East": "SENE EAST DISTRICT ASSEMBLY",
    "Sene West": "SENE WEST DISTRICT ASSEMBLY",
    "Shai Osudoku": "SHAI-OSUDOKU DISTRICT ASSEMBLY",
    "Shama": "SHAMA DISTRICT ASSEMBLY",
    "Sissala East": "SISSALA EAST MUNICIPAL ASSEMBLY",
    "Sissala West": "SISSALA WEST DISTRICT ASSEMBLY",
    "South Dayi": "SOUTH DAYI DISTRICT ASSEMBLY",
    "South Tongu": "SOUTH TONGU DISTRICT ASSEMBLY",
    "Suaman": "SUAMAN DISTRICT ASSEMBLY",
    "Suame": "SUAME MUNICIPAL ASSEMBLY",
    "Suhum": "SUHUM MUNICIPAL ASSEMBLY",
    "Sunyani": "SUNYANI MUNICIPAL ASSEMBLY",
    "Sunyani West": "SUNYANI WEST DISTRICT ASSEMBLY",
    "Tain": "TAIN DISTRICT ASSEMBLY",
    "Talensi": "TALENSI DISTRICT ASSEMBLY",
    "Tano North": "TANO NORTH MUNICIPAL ASSEMBLY",
    "Tano South": "TANO SOUTH MUNICIPAL ASSEMBLY",
    "Tarkwa-Nsuaem": "TARKWA-NSUAEM MUNICIPAL ASSEMBLY",
    "Tatale Sanguli": "TATALE-SANGULI DISTRICT ASSEMBLY",
    "Techiman": "TECHIMAN MUNICIPAL ASSEMBLY",
    "Techiman North": "TECHIMAN NORTH DISTRICT ASSEMBLY",
    "Tema West": "TEMA WEST DISTRICT ASSEMBLY",
    "Tempane": "TEMPANE DISTRICT ASSEMBLY",
    "Tolon": "TOLON DISTRICT ASSEMBLY",
    "Twifo Ati Morkwa": "TWIFO ATTI-MORKWA DISTRICT ASSEMBLY",
    "Twifo Heman Lower Denkyira": "TWIFO HEMAN LOWER DENKYIRA  DISTRICT ASSEMBLY",
    "Upper Denkyira East": "UPPER DEKYIRA EAST MUNICIPAL ASSEMBLY",
    "Upper Denkyira West": "UPPER DENKYIRA WEST DISTRICT ASSEMBLY",
    "Upper Manya Krobo": "UPPER MANYA KROBO DISTRICT ASSEMBLY",
    "Upper West Akim": "UPPER WEST AKIM DISTRICT ASSEMBLY",
    "Wa": "WA MUNICIPAL ASSEMBLY",
    "Wa East": "WA EAST DISTRICT ASSEMBLY",
    "Wa West": "WA WEST DISTRICT ASSEMBLY",
    "Wassa Amenfi East": "WASSA AMENFI EAST MUNICIPAL ASSEMBLY",
    "Wassa Amenfi West": "WASSA AMENFI WEST MUNICIPAL ASSEMBLY",
    "Wassa East": "WASSA EAST DISTRICT ASSEMBLY",
    "Weija Gbawe": "WEIJA-GBAWE MUNICIPAL ASSEMBLY",
    "Wenchi": "WENCHI MUNICIPAL ASSEMBLY",
    "West Akim": "WENCHI MUNICIPAL ASSEMBLY",
    "West Gonja": "WEST GONJA DISTRICT ASSEMBLY",
    "West Mamprusi": "WEST MAMPRUSI MUNICIPAL  ASSEMBLY",
    "Yendi": "YENDI MUNICIPAL ASSEMBLY",
    "Yilo Krobo": "YILO KROBO MUNICIPAL ASSEMBLY",
    "Yunyoo Nasuan": "YUNYOO-NANSUAN DISTRICT ASSEMBLY",
    "Zabzugu": "ZABZUGU DISTRICT ASSEMBLY",
}

reg_dict = {
    "Ahafo": "AHAFO",
    "Ashanti": "ASHANTI",
    "Bono": "BONO",
    "Bono East": "BONO EAST",
    "Central": "CENTRAL",
    "Eastern": "EASTERN",
    "Greater Accra": "GREATER ACCRA",
    "North East": "NORTH EAST",
    "Northern": "NORTHERN",
    "Oti": "OTI",
    "Savannah": "SAVANNAH",
    "Upper East": "UPPER EAST",
    "Upper West": "UPPER WEST",
    "Volta": "VOLTA",
    "Western": "WESTERN",
    "Western North": "WESTERN NORTH",
}
